branches:
    only:
        - master

sudo: required
dist: trusty

language: python

virtualenv:
    system_site_packages: true

before_install:
    - sudo add-apt-repository -y ppa:reddit/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq python-baseplate python-pyramid python-redis python-coverage python-mock

script:
    - python setup.py build
    - nosetests
